### ISSUE TITLE
Bitbake wpe-westeros-image fails to build

### ISSUE THREAD

**Issue by anwittmann** [Comcast/rdk-on-raspberrypi#4]
I'm running the installation guide. 
I think I installed all the packages correctly, but currently currently i'm stucked with the following error: 
`ERROR:Command Error: 'quilt --quiltrc /rpi-ml-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/libepoxy/1.5.3-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001_make_graphic_libs_configurable.patch
patching file src/dispatch_common.c
Hunk #1 FAILED at 173.
Hunk #2 FAILED at 180.
Hunk #3 FAILED at 193.
3 out of 3 hunks FAILED -- rejects in file src/dispatch_common.c
Patch 0001_make_graphic_libs_configurable.patch does not apply (enforce with -f)
DEBUG: Python function patch_do_patch finished
DEBUG: Python function do_patch finished
ERROR: Function failed: patch_do_patch`

**Comment by kraj** [comment]
@wouterlucas this patch in meta-wpe needs to be forward ported.

recipes-graphics/libepoxy/libepoxy/0001_make_graphic_libs_configurable.patch

**Comment by wouterlucas** [comment]
Which branch is this, master?

**Comment by kraj** [comment]
Yes

**Comment by wouterlucas** [comment]
Has been fixed by commit: https://github.com/WebPlatformForEmbedded/meta-wpe/commit/ea8912eb0195947f7d6240619a6e8f42d7d8590b

**Comment by kraj** [comment]
closing
