### ISSUE TITLE
Question on the error in bitbake wpe-westeros-image

### ISSUE THREAD

**Issue by Raspjones** [Comcast/rdk-on-raspberrypi#5]
Dear Experts,

I tried to install RDK on Raspberry Pi following the instructions.
But, I got an error when I added below item in conf/local.conf:

MACHINE = "raspberrypi3"

When I added "?" as below, then it works. Is this correct?

MACHINE ?= "raspberrypi3"

And I don't know where I need to put the below items:

BBMASK = "recipes-qt"
DISTRO_FEATURES_remove_rpi = "x11"

So, I ignored these two items, and run "bitbake wpe-westeros-image".
Definitely, it gives me errors as below:

NOTE: Bitbake server didn't start within 5 seconds, waiting for 90
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:
    Your system needs to support the en_US.UTF-8 locale.

Please help me how to resolve this.

Best regards,
Jones.

**Comment by kraj** [comment]
all these should be put in `local.conf` however it seems your build system does not have needed packages in this case it seems locales are missing, UTF-8 is commonly available locales. So you might have to check that first

**Comment by Raspjones** [comment]
Thanks, Kraj.
Currently, the locale is set to "LANG=en_GB.UTF-8", as I am in UK. If I change this to en_US.UTF-8, then I have enormous errors in bitbake wpe-westeros-image. I deleted all of them and re-start the procedures after I set the locale as en_US.UTF-8. But, I got enormous errors in much earlier process. Any good idea to resolve it?

**Comment by kraj** [comment]
I think you can install both en_GB and en_US and not set LANG in environment and let build use the defaults.

**Comment by Raspjones** [comment]
I re-installed Debian on Raspberry Pi 3 B+, and I selected US in the installation process. Also, I changed the SD card which was class 6 but now class U3, then the installation process looks much faster.

I don't know why, but I got another errors in "bitbake-layers add-layer ../meta-openembedded/meta-multimedia" as below:

--------------------

NOTE: Starting bitbake server...
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/pi/rpi-yocto/rpi-ml-build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 4348 at 2019-04-03 04:05:45.834245 ---
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: warrior (layer is compatible with thud)
Traceback (most recent call last):
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 284, in parseBaseConfiguration
    self.data = self.parseConfigurationFiles(self.prefiles, self.postfiles)
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 402, in parseConfigurationFiles
    % (c, " ".join(layerseries), " ".join(compat)))
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 120, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 83, in createDaemon
    function()
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 469, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset)
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 210, in __init__
    self.initConfigurationData()
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 375, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 317, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: warrior (layer is compatible with thud)
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: warrior (layer is compatible with thud)

ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/pi/rpi-yocto/rpi-ml-build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 4348 at 2019-04-03 04:05:45.834245 ---
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: warrior (layer is compatible with thud)
Traceback (most recent call last):
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 284, in parseBaseConfiguration
    self.data = self.parseConfigurationFiles(self.prefiles, self.postfiles)
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 402, in parseConfigurationFiles
    % (c, " ".join(layerseries), " ".join(compat)))
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/__init__.py", line 120, in fatal
    raise BBHandledException()
bb.BBHandledException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/daemonize.py", line 83, in createDaemon
    function()
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/server/process.py", line 469, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset)
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 210, in __init__
    self.initConfigurationData()
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/cooker.py", line 375, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/pi/rpi-yocto/poky/bitbake/lib/bb/cookerdata.py", line 317, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: warrior (layer is compatible with thud)
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: warrior (layer is compatible with thud)

----------------

I did not met this error before I re-installed the latest Debian on Raspberry Pi. I wonder how to resolve this.

Thank you for your help in advance.

Best regards,
Jones.

**Comment by Raspjones** [comment]
This is what I found:

1) SD card should be fast enough, otherwise, bitbake server is not running within appropriate timeout.
2) In the first installation of Debian, United State should be selected to avoid locale mismatch issue.
3) Yocto has been upgraded to warrior(2.7), but this RDK stack requires thud (2.6). So, I had to use the below command:
git clone -b thud git://git.yoctoproject.org/poky.git

After then, I could go to "bitbake wpe-westeros-image", but still I got some errors as below:
-----------
$ bitbake wpe-westeros-image
WARNING: Host distribution "raspbian-9" has not been validated with this version of the build system; you may possibly experience unexpected failures. It is recommended that you use a tested distribution.
ERROR: /home/pi/rpi-yocto/meta-openembedded/meta-python/recipes-devtools/python/python3-m2crypto_0.30.1.bb: Unable to determine endianness for architecture 'armv7l'
ERROR: /home/pi/rpi-yocto/meta-openembedded/meta-python/recipes-devtools/python/python3-m2crypto_0.30.1.bb: Please add your architecture to siteinfo.bbclass
ERROR: Failed to parse recipe: /home/pi/rpi-yocto/meta-openembedded/meta-python/recipes-devtools/python/python3-m2crypto_0.30.1.bb

Summary: There was 1 WARNING message shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
--------------

Perhaps, the latest software for Raspberry Pi 3 B+ has been upgraded and there are some compatibility issues. Is there anybody to help me to resolve this?

Best regards,
Jones.

**Comment by kraj** [comment]
Wait, are you trying to build on rpi3 itself ? then thats not what it is meant for. This is a cross build environment which you can use to build images on x86 laptops or hefty servers and then flash those images to SD-Card like you did flash debian. Then boot it. So it will be RDK image.

**Comment by Raspjones** [comment]
Hi, Kraj.

I see. How stupid I am. I installed Ubuntu 18.04 on a PC and I tried again. Almost of procedures were successful without any error or warning, but the latest procedure still shows warnings and error as below:

---------

$ bitbake wpe-westeros-image
Loading cache: 100% |############################################| Time: 0:00:00
Loaded 1753 entries from dependency cache.

WARNING: /home/jones/rpi-yocto/meta-openembedded/meta-oe/recipes-dbs/postgresql/postgresql_11.2.bb: Exception during build_dependencies for PERL_ARCHLIB

WARNING: /home/jones/rpi-yocto/meta-openembedded/meta-oe/recipes-dbs/postgresql/postgresql_11.2.bb: Error during finalise of /home/jones/rpi-yocto/meta-openembedded/meta-oe/recipes-dbs/postgresql/postgresql_11.2.bb

ERROR: ExpansionError during parsing /home/jones/rpi-yocto/meta-openembedded/meta-oe/recipes-dbs/postgresql/postgresql_11.2.bb
Traceback (most recent call last):
bb.data_smart.ExpansionError: Failure expanding variable PERL_ARCHLIB, expression was /home/jones/rpi-yocto/rpi-ml-build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/postgresql/11.2-r0/recipe-sysroot/usr/lib/perl5/${@get_perl_version(d)}/${@get_perl_arch(d)} which triggered exception NameError: name 'get_perl_arch' is not defined

Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

-----------

Do you have any idea to resolve these issues?

Best regards,
Jones

**Comment by kraj** [comment]
if you are using thud then use same branch for all repos.

**Comment by Raspjones** [comment]
Thank you, Kraj.
I still have issues, but let me try and close this ticket.
